default: &default
  adapter: postgresql
  encoding: unicode
  username: mohammad_yaser
  password: 456
  host: localhost
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: blog_development
test:
  <<: *default
  database: blog_test


production:
  <<: *default
  database: blog_production
  username: blog
  password: <%= ENV["BLOG_DATABASE_PASSWORD"] %>
