default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: mohammad_yaser
  password: 456
  host: localhost

development:
  <<: *default
  database: blog_database_development

test:
  <<: *default
  database: blog_database_test

production:
  <<: *default
  database: blog_database_production
  username: your_production_username
  password: <%= ENV['DATABASE_PASSWORD'] %>
